import {contracts,statusOrder,issueDefinitions,summarize,isComplete} from './data.js';
const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const paths={layout:'M3 3h7v7H3z M14 3h7v7h-7z M3 14h7v7H3z M14 14h7v7h-7z',layers:'m12 3 9 5-9 5-9-5 9-5z M3 12l9 5 9-5 M3 16l9 5 9-5',alert:'m12 3 10 18H2L12 3z M12 9v5 M12 17h.01',book:'M3 4h6q3 0 3 3v14q0-3-3-3H3V4z M21 4h-6q-3 0-3 3v14q0-3 3-3h6V4z',lock:'M6 10h12v11H6z M8 10V6a4 4 0 0 1 8 0v4 M12 14v3',play:'m8 4 13 8-13 8V4z',info:'M12 8h.01 M12 11v6 M22 12a10 10 0 1 0-20 0 10 10 0 0 0 20 0',filter:'M3 4h18l-7 8v7l-4 2v-9L3 4z',search:'M20 20l-5-5 M17 10a7 7 0 1 0-14 0 7 7 0 0 0 14 0',reset:'M3 10a9 9 0 1 1 2 8 M3 4v6h6',down:'m6 9 6 6 6-6',left:'m14 6-6 6 6 6',right:'m9 6 6 6-6 6',close:'m6 6 12 12 M18 6 6 18',download:'M12 3v12 m-5-5 5 5 5-5 M4 16v5h16v-5',donut:'M12 2v10h10 M9 3a10 10 0 1 0 12 12 M15 2a10 10 0 0 1 7 7h-7V2z',bars:'M4 20h16 M6 16V8 M12 16V3 M18 16v-6',file:'M5 2h9l5 5v15H5V2z M14 2v6h5 M8 12h8 M8 16h6',link:'m10 14 4-4 M8 16l-2 2a4 4 0 0 1-6-6l4-4a4 4 0 0 1 6 0 M16 8l2-2a4 4 0 0 1 6 6l-4 4a4 4 0 0 1-6 0',check:'m5 12 4 4L19 6',database:'M21 5c0 2-4 3-9 3S3 7 3 5s4-3 9-3 9 1 9 3z M3 5v14c0 2 4 3 9 3s9-1 9-3V5 M3 12c0 2 4 3 9 3s9-1 9-3'};
function icon(n){return `<svg class="icon" viewBox="0 0 24 24" aria-hidden="true"><path d="${paths[n]||paths.file}"/></svg>`;}
function icons(root=document){root.querySelectorAll('[data-icon]').forEach(el=>el.outerHTML=icon(el.dataset.icon));}
const colors={'Complete':'#398a78','In progress':'#d7b46c','On hold':'#be8f80','Not started':'#acb6c9'};
const state={region:[],status:[],use:[],issue:'',stage:'',kpi:'',search:'',view:'overview',sort:'id',dir:1,page:0};
let selected=null,selectedInterface=0,detailTab='traceability',guide=null;
const classStatus=s=>s.toLowerCase().replaceAll(' ','-');
const badge=s=>`<span class="badge ${classStatus(s)}">${esc(s)}</span>`;
const percent=(n,d)=>d?Math.round(n/d*100):0;
function filtered(){return contracts.filter(c=>
 (!state.region.length||state.region.includes(c.region))&&(!state.status.length||state.status.includes(c.status))&&(!state.use.length||state.use.includes(c.use))&&
 (!state.issue||c.issues.some(e=>e.type===state.issue))&&
 (!state.stage||state.stage==='conga'||(state.stage==='service'&&c.interfaces.some(i=>i.verified))||(state.stage==='collibra'&&isComplete(c)))&&
 (!state.kpi||state.kpi==='interfaces'&&c.interfaces.some(i=>i.verified)||state.kpi==='complete'&&isComplete(c)||state.kpi==='exceptions'&&c.issues.length>0)&&
 (state.view!=='exceptions'||c.issues.length>0)&&
 (!state.search||[c.id,c.name,c.state,c.region,c.demand,c.dsa,c.contractAsset,c.owner,...c.interfaces.flatMap(i=>[i.id,i.name,i.asset])].join(' ').toLowerCase().includes(state.search.toLowerCase()))
 );}
function initFilters(){
 $('#filter-controls').innerHTML=[['region','Region',['Midwest','South','Southeast']],['status','Linkage status',statusOrder],['use','Data use',['ADT','Care coordination','Provider directory','Direct messaging']]].map(([key,label,values])=>`<details class="filter" data-key="${key}"><summary><span data-filter-label="${key}">All ${label.toLowerCase()}s</span>${icon('down')}</summary><div class="filter-options"><button data-clear="${key}">Select all / clear filter</button>${values.map(v=>`<label><input type="checkbox" data-filter="${key}" value="${v}">${v}</label>`).join('')}</div></details>`).join('');
}
function render(){
 const rows=filtered(),s=summarize(rows);
 const labels={region:'All regions',status:'All statuses',use:'All data uses'};
 Object.keys(labels).forEach(key=>{$(`[data-filter-label="${key}"]`).textContent=state[key].length?state[key].length===1?state[key][0]:`${state[key].length} selected`:labels[key];document.querySelectorAll(`[data-filter="${key}"]`).forEach(el=>el.checked=state[key].includes(el.value));});
 const chips=[];
 for(const key of ['region','status','use'])for(const value of state[key])chips.push(`<button class="chip" data-remove="${key}" data-value="${esc(value)}">${esc(value)} <span>×</span></button>`);
 if(state.issue)chips.push(`<button class="chip" data-remove="issue">${esc(state.issue)} <span>×</span></button>`);
 if(state.stage)chips.push(`<button class="chip" data-remove="stage">${{conga:'Signed agreements',service:'Verified ServiceNow links',collibra:'Complete Collibra traceability'}[state.stage]} <span>×</span></button>`);
 if(state.kpi)chips.push(`<button class="chip" data-remove="kpi">${{interfaces:'Has verified interfaces',complete:'Complete traceability',exceptions:'Has open exceptions'}[state.kpi]} <span>×</span></button>`);
 $('#active-filters').innerHTML=chips.join('');
 const kpis=[['','Contracts in scope',s.contracts,'HIE master agreements','file',''],['interfaces','Verified interfaces',s.interfaces,`<b>${s.linkedContracts} of ${s.contracts}</b> contracts have a verified link`,'link',''],['complete','End-to-end coverage',`${percent(s.complete,s.contracts)}<small>%</small>`,`<b>${s.complete} of ${s.contracts}</b> contracts fully reconciled`,'check','complete'],['exceptions','Open exceptions',s.exceptions,`Across <b>${s.affected}</b> ${s.affected===1?'contract':'contracts'}`,'alert','exceptions']];
 $('#kpis').innerHTML=kpis.map(([key,title,value,foot,ic,cl])=>`<button class="kpi ${cl}" data-kpi="${key}" aria-label="${title}: ${String(value).replace(/<[^>]*>/g,'')}. ${key?'Filter to these contracts':'Show metric definition'}" title="${key?'Click to filter; click again to clear':'View metric definitions'}"><span class="kpi-top">${title}<span class="kpi-icon">${icon(ic)}</span></span><span class="value">${value}</span><span class="kpi-foot">${foot}</span></button>`).join('');
 const stages=[['conga','Conga',s.contracts,'signed agreements','file'],['service','ServiceNow',s.linkedContracts,'contracts with verified links','layers'],['collibra','Collibra',s.complete,'fully governed contracts','database']];
 $('#stages').innerHTML=stages.map(([key,name,n,sub,ic],i)=>`${i?'<span class="flow-arrow" aria-hidden="true">→</span>':''}<button class="stage" data-stage="${key}" title="Filter to ${sub}"><span class="stage-logo">${icon(ic)}</span><span><span class="stage-title">${name}<span>${String(i+1).padStart(2,'0')}</span></span><span class="stage-sub"><b>${n}</b> ${sub}</span></span></button>`).join('');
 let offset=0;const stops=statusOrder.map(st=>{const n=rows.filter(c=>c.status===st).length;const start=offset;offset+=s.contracts?n/s.contracts*100:0;return `${colors[st]} ${start}% ${offset}%`;});
 $('#status-chart').innerHTML=`<div class="donut-layout"><div class="donut" style="background:${s.contracts?`conic-gradient(${stops.join(',')})`:'#edf1ef'}" role="img" aria-label="Linkage status distribution"><div class="donut-hole"><strong>${s.contracts}</strong><span>contracts</span></div></div><div class="legend">${statusOrder.map(st=>`<button data-status="${st}" title="Filter ${st} contracts"><span class="swatch" style="background:${colors[st]}"></span>${st}<b>${rows.filter(c=>c.status===st).length}</b></button>`).join('')}</div></div><span class="chart-hint">Select a status to filter the report</span>`;
 const issues=Object.keys(issueDefinitions).map(type=>[type,rows.reduce((sum,c)=>sum+c.issues.filter(e=>e.type===type).length,0)]).sort((a,b)=>b[1]-a[1]);
 const max=Math.max(...issues.map(x=>x[1]),1);
 $('#exception-chart').innerHTML=`<div class="exception-bars">${issues.map(([type,n])=>`<button class="bar-button" data-issue="${type}" title="Filter: ${type}, ${n} open"><div class="bar-label"><span>${type}</span><b>${n}</b></div><div class="bar-track"><div class="bar-fill" style="width:${n/max*100}%;background:${type==='Missing interface'||type==='Unverified match'?'#bf9481':'#a6bbaa'}"></div></div></button>`).join('')}</div>`;
 $('#region-chart').innerHTML=`<div class="region-bars">${['Midwest','South','Southeast'].map(region=>{const subset=rows.filter(c=>c.region===region),complete=subset.filter(isComplete).length;return `<button class="bar-button" data-region="${region}" title="Filter ${region}: ${complete} of ${subset.length} complete"><div class="bar-label"><span>${region}</span><b>${complete}<span style="color:#a3b1ae"> / ${subset.length}</span></b></div><div class="bar-track"><div class="bar-fill" style="width:${percent(complete,subset.length)}%"></div><div class="remaining" style="width:${subset.length?100-percent(complete,subset.length):0}%"></div></div></button>`;}).join('')}</div><div class="region-legend"><span><i class="swatch" style="background:#33887b"></i>Complete</span><span><i class="swatch" style="background:#e0ebe5"></i>Remaining</span></div><span class="chart-hint">Select a region to cross-filter</span>`;
 document.querySelectorAll('.charts,.path-summary').forEach(el=>el.hidden=state.view!=='overview');
 // hidden must override the layout display declarations.
 document.querySelectorAll('.charts,.path-summary').forEach(el=>el.style.display=state.view!=='overview'?'none':'');
 document.querySelectorAll('[data-nav]').forEach(el=>{el.classList.toggle('active',el.dataset.nav===state.view);el.setAttribute('aria-current',el.dataset.nav===state.view?'page':'false');});
 $('#nav-count').textContent=summarize(contracts).exceptions;
 renderTable(rows);
}
function sortValue(c){switch(state.sort){case 'name':return c.name;case 'region':return c.region;case 'interfaces':return c.interfaces.filter(i=>i.verified).length;case 'catalog':return c.interfaces.filter(i=>i.related).length;case 'status':return statusOrder.indexOf(c.status);case 'issues':return c.issues.length;default:return c.id;}}
function renderTable(rows){
 const queue=state.view==='exceptions';
 $('#register-title').textContent=queue?'Reconciliation exception queue':'Contract traceability register';
 $('#register-description').textContent=queue?'One row per open exception. Select a record to inspect the evidence and next action.':'Select a contract to inspect its source records and evidence.';
 const sorted=[...rows].sort((a,b)=>{const av=sortValue(a),bv=sortValue(b);return (typeof av==='number'?av-bv:av.localeCompare(bv))*state.dir;});
 const items=queue?sorted.flatMap(c=>c.issues.filter(e=>!state.issue||e.type===state.issue).map(e=>({c,e}))):sorted;
 const pages=Math.max(1,Math.ceil(items.length/8));state.page=Math.min(state.page,pages-1);
 const heads=queue?[['name','Contract / agreement'],['','Exception'],['','Severity'],['','Owner'],['','Age'],['status','Linkage status'],['','']]:[['name','Contract / agreement'],['region','Region'],['interfaces','Verified interfaces'],['catalog','Catalog links'],['status','Linkage status'],['issues','Exceptions'],['','']];
 $('#table-head').innerHTML=`<tr>${heads.map(([key,label])=>`<th>${key?`<button data-sort="${key}" aria-label="Sort by ${label}">${label}<span aria-hidden="true">${state.sort===key?(state.dir===1?'↑':'↓'):'↕'}</span></button>`:label}</th>`).join('')}</tr>`;
 $('#table-body').innerHTML=items.length?items.slice(state.page*8,(state.page+1)*8).map(item=>{const c=queue?item.c:item;return `<tr class="contract-row"><td><button class="contract-name" data-contract="${c.id}" ${queue?'data-tab="exceptions"':''}>${esc(c.name)}</button><span class="contract-id">${c.id}</span></td>${queue?`<td>${item.e.type}</td><td><span class="severity ${item.e.severity}">${item.e.severity}</span></td><td>${item.e.owner}</td><td>${item.e.age} days</td><td>${badge(c.status)}</td>`:`<td class="region-cell">${c.region}<small>${c.state} · ${c.use}</small></td><td><span class="fraction">${c.interfaces.filter(i=>i.verified).length} <span>/ ${c.interfaces.length}</span></span></td><td><span class="fraction">${c.interfaces.filter(i=>i.related).length} <span>/ ${c.interfaces.length}</span></span></td><td>${badge(c.status)}</td><td>${c.issues.length?`<span class="issue-pill">${c.issues.length}</span>`:'<span class="no-issues">—</span>'}</td>`}<td><button class="drill-button" data-contract="${c.id}" ${queue?'data-tab="exceptions"':''} aria-label="Open ${c.name} details">${icon('right')}</button></td></tr>`;}).join(''):`<tr><td colspan="7" class="empty"><strong>No matching records</strong>Try clearing a filter or changing your search.<br><button class="text-button" data-reset="true" style="margin-top:12px">Reset all filters</button></td></tr>`;
 $('#row-count').textContent=items.length?`${state.page*8+1}–${Math.min((state.page+1)*8,items.length)} of ${items.length} ${queue?'exceptions':'contracts'} · Sample data`:`0 ${queue?'exceptions':'contracts'} · Sample data`;
 $('#page-count').textContent=`${state.page+1} / ${pages}`;$('#prev').disabled=state.page===0;$('#next').disabled=state.page===pages-1;
}
function reset(){Object.assign(state,{region:[],status:[],use:[],issue:'',stage:'',kpi:'',search:'',page:0});$('#search').value='';render();}
function toggle(key,val){state[key]=state[key]===val?'':val;state.page=0;render();}
function openDetail(id,tab='traceability') {selected=contracts.find(c=>c.id===id);selectedInterface=0;detailTab=tab;renderDetail();if(!$('#detail').open)$('#detail').showModal();$('#detail').scrollTop=0;}
function renderDetail(){
 const c=selected,i=c.interfaces[selectedInterface];if(!c)return;
 $('#detail-content').innerHTML=`<div class="detail-head"><div class="detail-topline"><span>CONTRACT DRILL-THROUGH · SYNTHETIC RECORD</span><button class="icon-button" data-close-detail aria-label="Close contract details">${icon('close')}</button></div><h2>${c.name}</h2><div class="detail-sub"><span>${c.id}</span><span>${c.region} / ${c.state}</span>${badge(c.status)}</div><div class="detail-tabs" role="tablist" aria-label="Contract detail views">${[['traceability','Traceability'],['exceptions',`Exceptions (${c.issues.length})`],['notes','Interview notes']].map(([key,label])=>`<button role="tab" aria-selected="${detailTab===key}" class="${detailTab===key?'active':''}" data-detail-tab="${key}">${label}</button>`).join('')}</div></div><div class="detail-body">${guide!==null&&guide>0?guideMarkup(true):''}${detailTab==='traceability'?traceabilityMarkup(c,i):detailTab==='exceptions'?exceptionsMarkup(c):notesMarkup(c)}</div>`;
}
function traceabilityMarkup(c,i){return `<div class="detail-intro">${isComplete(c)?'<strong>Evidence chain complete.</strong> The agreement is linked to verified interfaces, catalog relationships, and an owner attestation.':`<strong>${c.issues.length} open ${c.issues.length===1?'exception':'exceptions'}.</strong> ${esc(c.issues[0].evidence)}`}</div><div class="source-cards">
 <article class="source-card"><div class="source-head"><span class="source-number">1</span><strong>Conga · Signed agreement</strong><small>LEGAL SOURCE</small></div><div class="source-content"><dl class="key-values"><div><dt>Contract ID</dt><dd>${c.id}</dd></div><div><dt>Agreement type</dt><dd>HIE master agreement</dd></div><div><dt>Signed date</dt><dd>${c.signed}</dd></div><div><dt>Contract owner</dt><dd>${c.legalOwner}</dd></div><div><dt>Permitted data use</dt><dd>${c.use}</dd></div><div><dt>Demand reference</dt><dd>${c.demand}</dd></div></dl><div class="evidence-line">Sample evidence: agreement §4.2 · data exchange schedule A</div></div></article>
 <article class="source-card"><div class="source-head"><span class="source-number">2</span><strong>ServiceNow · Interface services</strong><small>TECHNICAL SOURCE</small></div><div class="source-content">${i?`<div class="interface-picker">${c.interfaces.map((v,idx)=>`<button data-interface="${idx}" class="${selectedInterface===idx?'active':''}" aria-pressed="${selectedInterface===idx}">${v.id} · ${v.verified?'Verified':'Candidate'}</button>`).join('')}</div><dl class="key-values"><div><dt>Interface ID / name</dt><dd>${i.id} · ${i.name}</dd></div><div><dt>Link confidence</dt><dd>${i.verified?'Verified by owner':'Candidate — confirmation required'}</dd></div><div><dt>Transfer / direction</dt><dd>${i.protocol}<br>${i.direction}</dd></div><div><dt>Technical owner</dt><dd>${i.owner}</dd></div><div><dt>Sample endpoint (non-routable)</dt><dd>${i.endpoint}</dd></div><div><dt>Demand reference</dt><dd>${i.demand}</dd></div></dl><div class="detail-fields"><strong>DATA ELEMENT METADATA · NO PATIENT VALUES</strong>${i.fields.map(esc).join(' &nbsp; / &nbsp; ')}</div><div class="evidence-line"><span>Match basis:</span> ${c.matchBasis}${i.verified?`<br>Owner verification recorded ${i.verifiedOn}`:''}</div>`:`<span class="state-note">No interface identified</span><p style="margin-top:12px;color:#81978b">The signed contract is in scope. Interface discovery and owner confirmation are still required.</p>`}</div></article>
 <article class="source-card"><div class="source-head"><span class="source-number">3</span><strong>Collibra · Governed relationships</strong><small>GOVERNANCE CATALOG</small></div><div class="source-content"><dl class="key-values"><div><dt>HIE Contract asset</dt><dd>${c.contractAsset}</dd></div><div><dt>Interface Services asset</dt><dd>${i?.asset||'Not registered'}</dd></div><div><dt>Contract → interface relationship</dt><dd>${i?.related?'Published and linked':'Not published'}</dd></div><div><dt>Data sharing agreement</dt><dd>${c.dsa} · ${isComplete(c)?'Approved':'In review'}</dd></div><div><dt>Accountable steward</dt><dd>${c.owner}</dd></div><div><dt>Owner attestation</dt><dd>${c.attested?'Recorded · Sep 16, 2026':'Pending'}</dd></div></dl><div class="evidence-line"><span>End-to-end result:</span> ${isComplete(c)?'All linked interfaces verified; catalog relationships and attestation complete.':'Incomplete until the documented exceptions are cleared.'}</div></div></article></div>`;}
function exceptionsMarkup(c){return c.issues.length?c.issues.map(e=>`<article class="exception-card"><div class="exception-title"><h3>${e.type}</h3><span class="severity ${e.severity}">${e.severity}</span></div><div class="exception-meta"><span>${e.id}</span><span>${e.age} days open</span><span>${e.owner}</span></div><p>${e.evidence}</p><div class="next-action"><strong>Next reconciliation action</strong>${e.action}</div></article>`).join(''):'<div class="detail-intro"><strong>No open exceptions.</strong><br>All sample evidence checks passed for this agreement. The linked interfaces, catalog relationships, and owner attestation are complete.</div>';}
function notesMarkup(c){return `<div class="interview-card"><h3>A concise way to explain this example</h3><p>“This sample agreement starts in Conga, where I establish the signed contract and permitted data use. I use the demand reference, interface metadata, and owner confirmation to verify the ServiceNow link. Then I check that Collibra captures the contract, interface, and their relationship.${isComplete(c)?' Here, the evidence chain and attestation are complete.':` In this case, ${c.issues.map(e=>e.type.toLowerCase()).join(' and ')} prevents the record from being considered fully reconciled.`}”</p></div><div class="interview-card"><h3>What to emphasize</h3><ul><li>Start with the master agreement and preserve its source identifier.</li><li>A similar vendor name is supporting evidence; it is not sufficient by itself.</li><li>One contract can connect to multiple technical interfaces. Check each path.</li><li>Keep the exception, accountable owner, evidence, and next action visible.</li></ul></div><div class="detail-intro">Use this as a demonstration of your approach. These sample counts and outcomes are not claims about Ascension’s production results.</div>`;}
const guideSteps=[
 {title:'Start with the reconciliation question',body:'The cards count contracts, distinct verified interfaces, complete evidence chains, and individual exceptions. Every slicer changes the same report context.',talk:'“I use this view to see which agreements are traceable to technical data flows and where evidence is still missing.”'},
 {title:'Follow a complete evidence chain',id:'CGA-2026-001',body:'This sample contract has two verified ServiceNow interfaces. Switch between them, then inspect the catalog relationship and owner attestation below.',talk:'“I preserve the contract ID, confirm the demand reference with the interface owner, and record each accepted relationship in Collibra.”'},
 {title:'Explain a governance gap',id:'CGA-2026-013',body:'The interface is verified in ServiceNow, but the Interface Services asset is missing in Collibra. Open the Exceptions tab to see the accountable team and next action.',talk:'“A technical match alone does not close the work. The catalog record and relationship must also be complete.”'},
 {title:'Distinguish a candidate from evidence',id:'CGA-2026-020',body:'A vendor alias and region suggest a match, but the owner has not confirmed it. The candidate is excluded from the verified interface KPI.',talk:'“I keep uncertain matches on hold and document what is needed to verify them, rather than treating a name match as proof.”'}
];
function guideMarkup(inDetail=false){const s=guideSteps[guide];return `<div class="${inDetail?'interview-card guided-card':''}"><div class="eyebrow">INTERVIEW WALKTHROUGH · ${guide+1} OF 4</div><h3 style="font-size:15px;margin-bottom:10px;color:#315e46;text-transform:none;letter-spacing:0">${s.title}</h3><p>${s.body}</p><div class="talk-track" style="${inDetail?'font-size:11px;line-height:1.8;background:#eff6ef;padding:12px;border-radius:5px;margin-top:12px;color:#567252':''}">${s.talk}</div>${inDetail?`<div class="coach-controls"><button class="text-button" data-guide-prev>Previous</button><button class="text-button" data-guide-end>End walkthrough</button><button class="primary" data-guide-next>${guide===3?'Finish walkthrough':'Next example'} ${icon('right')}</button></div>`:''}</div>`;}
function setGuide(n){
 if(n>3){endGuide();toast('Walkthrough complete. Explore the slicers and drill-through views at your own pace.');return;}
 guide=Math.max(n,0);
 if(guide===0){if($('#detail').open)$('#detail').close();$('#coach').hidden=false;$('#coach-content').innerHTML=guideMarkup();$('#coach-prev').disabled=true;$('#coach-dots').innerHTML=guideSteps.map((_,idx)=>`<span class="${guide===idx?'active':''}"></span>`).join('');}
 else {$('#coach').hidden=true;openDetail(guideSteps[guide].id);}
}
function endGuide(){guide=null;$('#coach').hidden=true;if($('#detail').open)$('#detail').close();}
function info(kind){
 $('#info-content').innerHTML=kind==='about'?`<div class="eyebrow">A WORKING INTERVIEW PROTOTYPE</div><h2>Practice the process with confidence.</h2><p>This browser-based report models the Conga → ServiceNow → Collibra reconciliation workflow discussed for your Ascension D SHARP work. It resembles a Power BI report, but is not a Power BI file or a live enterprise integration.</p><p>The 25 master agreements, organization names, identifiers, dates, exception ages, and KPI outcomes are entirely synthetic. There are no patient records, production endpoints, or confidential source documents.</p><div class="schema-strip">Contract (1) → Interface links (many) → Catalog relationships</div><p>Use the slicers or charts to cross-filter. Select a contract to inspect technical metadata, matching evidence, and a next action. Export CSV downloads the current filtered register.</p><p>Sample snapshot: September 18, 2026. Filters reset when you reload the page.</p>`:`<div class="eyebrow">HOW TO READ THE REPORT</div><h2>Metric definitions</h2><p>All cards and charts reflect the current filters. Counts come from the same sample dataset. No percentage is a production performance claim.</p><dl class="definitions-list"><dt>Contracts in scope</dt><dd>Distinct HIE master agreements in the filtered dataset. Each contract has a unique Conga ID.</dd><dt>Verified interfaces</dt><dd>Distinct ServiceNow interface IDs with an owner-verified contract link. Unconfirmed candidate interfaces are excluded. The subtitle counts contracts with at least one accepted link.</dd><dt>End-to-end coverage</dt><dd>Complete contracts ÷ contracts in scope. Complete requires at least one interface, every interface verified, every Collibra asset and relationship present, an owner attestation, and no open exceptions. An empty selection displays 0% with 0 of 0 contracts.</dd><dt>Open exceptions</dt><dd>Individual open issues, counted once per contract and exception type. One contract may have multiple issues; the affected-contract count is shown separately. Filtering by issue type selects contracts with that issue; their other issues still contribute to the cards.</dd><dt>Linkage status</dt><dd>Complete: all evidence checks passed. In progress: verified links exist but catalog or attestation work remains. On hold: an unverified match or an explicitly held owner review blocks progress. Not started: no interface candidate has been identified.</dd><dt>Register fractions</dt><dd>Verified interfaces = accepted / identified interfaces. Catalog links = published contract-to-interface relationships / identified interfaces. A 0 / 0 record has no identified interface and is not complete.</dd><dt>Region coverage</dt><dd>Complete contracts / all filtered contracts within that region. Status, region, and exception chart selections cross-filter the entire report. Select again or remove the filter chip to clear.</dd></dl>`;
 $('#info-dialog').showModal();
}
function toast(msg){$('#toast').textContent=msg;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),4500);}
function exportCsv(){const rows=filtered(),queue=state.view==='exceptions';const headers=queue?['Contract ID','Organization','Region','Exception ID','Exception type','Severity','Owner','Age (days)','Next action']:['Contract ID','Organization','Region','State','Data use','Linkage status','Verified interfaces','Identified interfaces','Published relationships','Open exceptions','Exception types'];const data=queue?rows.flatMap(c=>c.issues.filter(e=>!state.issue||e.type===state.issue).map(e=>[c.id,c.name,c.region,e.id,e.type,e.severity,e.owner,e.age,e.action])):rows.map(c=>[c.id,c.name,c.region,c.state,c.use,c.status,c.interfaces.filter(i=>i.verified).length,c.interfaces.length,c.interfaces.filter(i=>i.related).length,c.issues.length,c.issues.map(e=>e.type).join('; ')]);const text=[headers,...data].map(row=>row.map(v=>'"'+String(v).replaceAll('"','""')+'"').join(',')).join('\r\n');const url=URL.createObjectURL(new Blob(['\uFEFF'+text],{type:'text/csv;charset=utf-8;'}));const a=document.createElement('a');a.href=url;a.download=`synthetic-${queue?'exceptions':'traceability'}-2026-09-18.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast(`Exported ${data.length} sample ${queue?'exceptions':'contracts'}.`);}
document.addEventListener('click',e=>{
 const b=e.target.closest('button');
 if(!e.target.closest('.filter'))document.querySelectorAll('.filter').forEach(d=>d.open=false);
 if(!b)return;
 const d=b.dataset;
 if('nav'in d){state.view=d.nav;state.page=0;render();}
 if('clear'in d){state[d.clear]=[];state.page=0;render();}
 if('remove'in d){if(Array.isArray(state[d.remove]))state[d.remove]=state[d.remove].filter(v=>v!==d.value);else state[d.remove]='';state.page=0;render();}
 if('kpi'in d){if(!d.kpi)info('definitions');else toggle('kpi',d.kpi);}
 if('stage'in d)toggle('stage',d.stage);
 if('status'in d){state.status=state.status.length===1&&state.status[0]===d.status?[]:[d.status];state.page=0;render();}
 if('region'in d){state.region=state.region.length===1&&state.region[0]===d.region?[]:[d.region];state.page=0;render();}
 if('issue'in d)toggle('issue',d.issue);
 if('sort'in d){state.dir=state.sort===d.sort?-state.dir:1;state.sort=d.sort;render();}
 if('contract'in d){guide=null;$('#coach').hidden=true;openDetail(d.contract,d.tab||'traceability');}
 if('detailTab'in d){detailTab=d.detailTab;renderDetail();}
 if('interface'in d){selectedInterface=Number(d.interface);renderDetail();}
 if('closeDetail'in d){guide=null;$('#coach').hidden=true;$('#detail').close();}
 if('reset'in d)reset();
 if('guideNext'in d)setGuide(guide+1);
 if('guidePrev'in d)setGuide(guide-1);
 if('guideEnd'in d)endGuide();
});
document.addEventListener('change',e=>{if(e.target.dataset.filter){const key=e.target.dataset.filter,v=e.target.value;state[key]=e.target.checked?[...state[key],v]:state[key].filter(x=>x!==v);state.page=0;render();}});
$('#search').addEventListener('input',e=>{state.search=e.target.value.trim();state.page=0;render();});
$('#reset').onclick=reset;$('#prev').onclick=()=>{state.page--;render();};$('#next').onclick=()=>{state.page++;render();};$('#export').onclick=exportCsv;
$('#definitions').onclick=()=>info('definitions');$('#about').onclick=()=>info('about');$('#close-info').onclick=()=>$('#info-dialog').close();
$('#walkthrough').onclick=()=>{state.view='overview';reset();setGuide(0);};$('#coach-next').onclick=()=>setGuide(guide+1);$('#coach-prev').onclick=()=>setGuide(guide-1);$('#close-coach').onclick=endGuide;
$('#detail').addEventListener('cancel',()=>{guide=null;$('#coach').hidden=true;});
$('#info-dialog').addEventListener('click',e=>{if(e.target===$('#info-dialog')){const r=e.target.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)e.target.close();}});
initFilters();icons();render();
